
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AT DATE FLOAT FOR FROM IDENTIFIER INTEGER KEYWORD_BOOK KEYWORD_CANCEL KEYWORD_CONFIRM KEYWORD_EXIT KEYWORD_HELP KEYWORD_HISTORY KEYWORD_LIST KEYWORD_PAY KEYWORD_TICKET KEYWORD_TICKETS KEYWORD_VIEW ON RESERVATION RESERVATIONS SCHEDULE STRING SYM_END TIME TO\ncommand : book_command\n        | confirm_command\n        | pay_command\n        | cancel_command\n        | list_command\n        | view_command\n        | history_command\n        | help_command\n        | exit_command\n\nidentifier_list : IDENTIFIER identifier_list\n                | IDENTIFIER\n                | STRING\n\nbook_command : KEYWORD_BOOK KEYWORD_TICKET FOR identifier_list FROM identifier_list TO identifier_list ON DATE AT TIME FOR identifier_list SYM_END\n            | KEYWORD_BOOK INTEGER KEYWORD_TICKETS FOR identifier_list FROM identifier_list TO identifier_list ON DATE AT TIME FOR identifier_list SYM_END\n\nconfirm_command : KEYWORD_CONFIRM RESERVATION FOR identifier_list FOR identifier_list SYM_END\n                | KEYWORD_CONFIRM INTEGER RESERVATIONS FOR identifier_list FOR identifier_list SYM_END\npay_command : KEYWORD_PAY RESERVATION FOR identifier_list FOR identifier_list SYM_ENDcancel_command : KEYWORD_CANCEL RESERVATION FOR identifier_list FOR identifier_list SYM_END\nlist_command : KEYWORD_LIST identifier_list SCHEDULE SYM_END\nview_command : KEYWORD_VIEW SCHEDULE FOR identifier_list SYM_ENDhistory_command : KEYWORD_HISTORY FOR identifier_list SYM_ENDhelp_command : KEYWORD_HELP SYM_ENDexit_command : KEYWORD_EXIT SYM_END'
    
_lr_action_items = {'KEYWORD_BOOK':([0,],[11,]),'KEYWORD_CONFIRM':([0,],[12,]),'KEYWORD_PAY':([0,],[13,]),'KEYWORD_CANCEL':([0,],[14,]),'KEYWORD_LIST':([0,],[15,]),'KEYWORD_VIEW':([0,],[16,]),'KEYWORD_HISTORY':([0,],[17,]),'KEYWORD_HELP':([0,],[18,]),'KEYWORD_EXIT':([0,],[19,]),'$end':([1,2,3,4,5,6,7,8,9,10,31,32,49,51,58,67,69,70,73,86,88,],[0,-1,-2,-3,-4,-5,-6,-7,-8,-9,-22,-23,-19,-21,-20,-15,-17,-18,-16,-13,-14,]),'KEYWORD_TICKET':([11,],[20,]),'INTEGER':([11,12,],[21,23,]),'RESERVATION':([12,13,14,],[22,24,25,]),'IDENTIFIER':([15,27,30,33,35,37,38,41,44,46,52,54,56,57,60,62,65,72,82,85,],[27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,]),'STRING':([15,27,30,33,35,37,38,41,44,46,52,54,56,57,60,62,65,72,82,85,],[28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,]),'SCHEDULE':([16,26,27,28,40,],[29,39,-11,-12,-10,]),'FOR':([17,20,22,24,25,27,28,29,34,36,40,45,47,48,55,80,83,],[30,33,35,37,38,-11,-12,41,44,46,-10,54,56,57,62,82,85,]),'SYM_END':([18,19,27,28,39,40,42,50,61,63,64,68,84,87,],[31,32,-11,-12,49,-10,51,58,67,69,70,73,86,88,]),'KEYWORD_TICKETS':([21,],[34,]),'RESERVATIONS':([23,],[36,]),'FROM':([27,28,40,43,53,],[-11,-12,-10,52,60,]),'TO':([27,28,40,59,66,],[-11,-12,-10,65,72,]),'ON':([27,28,40,71,75,],[-11,-12,-10,74,77,]),'DATE':([74,77,],[76,79,]),'AT':([76,79,],[78,81,]),'TIME':([78,81,],[80,83,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'book_command':([0,],[2,]),'confirm_command':([0,],[3,]),'pay_command':([0,],[4,]),'cancel_command':([0,],[5,]),'list_command':([0,],[6,]),'view_command':([0,],[7,]),'history_command':([0,],[8,]),'help_command':([0,],[9,]),'exit_command':([0,],[10,]),'identifier_list':([15,27,30,33,35,37,38,41,44,46,52,54,56,57,60,62,65,72,82,85,],[26,40,42,43,45,47,48,50,53,55,59,61,63,64,66,68,71,75,84,87,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> book_command','command',1,'p_command','lex.py',146),
  ('command -> confirm_command','command',1,'p_command','lex.py',147),
  ('command -> pay_command','command',1,'p_command','lex.py',148),
  ('command -> cancel_command','command',1,'p_command','lex.py',149),
  ('command -> list_command','command',1,'p_command','lex.py',150),
  ('command -> view_command','command',1,'p_command','lex.py',151),
  ('command -> history_command','command',1,'p_command','lex.py',152),
  ('command -> help_command','command',1,'p_command','lex.py',153),
  ('command -> exit_command','command',1,'p_command','lex.py',154),
  ('identifier_list -> IDENTIFIER identifier_list','identifier_list',2,'p_identifier_list','lex.py',162),
  ('identifier_list -> IDENTIFIER','identifier_list',1,'p_identifier_list','lex.py',163),
  ('identifier_list -> STRING','identifier_list',1,'p_identifier_list','lex.py',164),
  ('book_command -> KEYWORD_BOOK KEYWORD_TICKET FOR identifier_list FROM identifier_list TO identifier_list ON DATE AT TIME FOR identifier_list SYM_END','book_command',15,'p_book_command','lex.py',187),
  ('book_command -> KEYWORD_BOOK INTEGER KEYWORD_TICKETS FOR identifier_list FROM identifier_list TO identifier_list ON DATE AT TIME FOR identifier_list SYM_END','book_command',16,'p_book_command','lex.py',188),
  ('confirm_command -> KEYWORD_CONFIRM RESERVATION FOR identifier_list FOR identifier_list SYM_END','confirm_command',7,'p_confirm_command','lex.py',247),
  ('confirm_command -> KEYWORD_CONFIRM INTEGER RESERVATIONS FOR identifier_list FOR identifier_list SYM_END','confirm_command',8,'p_confirm_command','lex.py',248),
  ('pay_command -> KEYWORD_PAY RESERVATION FOR identifier_list FOR identifier_list SYM_END','pay_command',7,'p_pay_command','lex.py',266),
  ('cancel_command -> KEYWORD_CANCEL RESERVATION FOR identifier_list FOR identifier_list SYM_END','cancel_command',7,'p_cancel_command','lex.py',273),
  ('list_command -> KEYWORD_LIST identifier_list SCHEDULE SYM_END','list_command',4,'p_list_command','lex.py',281),
  ('view_command -> KEYWORD_VIEW SCHEDULE FOR identifier_list SYM_END','view_command',5,'p_view_command','lex.py',289),
  ('history_command -> KEYWORD_HISTORY FOR identifier_list SYM_END','history_command',4,'p_history_command','lex.py',296),
  ('help_command -> KEYWORD_HELP SYM_END','help_command',2,'p_help_command','lex.py',301),
  ('exit_command -> KEYWORD_EXIT SYM_END','exit_command',2,'p_exit_command','lex.py',318),
]
